/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guru;

/**
 *
 * @author Arif Rachmat Darmawa
 */
public class edit_guru extends javax.swing.JFrame {

    /**
     * Creates new form edit_guru
     */
    public edit_guru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_editGuru = new javax.swing.JPanel();
        lbl_editGuru = new javax.swing.JLabel();
        sp_pembatas = new javax.swing.JSeparator();
        lbl_kodeGuru = new javax.swing.JLabel();
        tf_kodeGuru = new javax.swing.JTextField();
        lbl_namaGuru = new javax.swing.JLabel();
        tf_namaGuru = new javax.swing.JTextField();
        lbl_alamat = new javax.swing.JLabel();
        lbl_nomorTelepon = new javax.swing.JLabel();
        tf_nomorTelepon = new javax.swing.JTextField();
        btn_editData = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_editGuru.setBackground(new java.awt.Color(255, 255, 255));

        lbl_editGuru.setBackground(new java.awt.Color(0, 0, 0));
        lbl_editGuru.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_editGuru.setText("Edit Guru");

        lbl_kodeGuru.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_kodeGuru.setText("Kode Guru ( Contoh Penamaan : KDG_001 )");

        tf_kodeGuru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_namaGuru.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_namaGuru.setText("Nama Guru");

        tf_namaGuru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_alamat.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_alamat.setText("Alamat");

        lbl_nomorTelepon.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_nomorTelepon.setText("Nomor Telepon");

        tf_nomorTelepon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_editData.setBackground(new java.awt.Color(0, 140, 186));
        btn_editData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_editData.setText("Edit Data");

        btn_kembali.setBackground(new java.awt.Color(244, 67, 54));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnl_editGuruLayout = new javax.swing.GroupLayout(pnl_editGuru);
        pnl_editGuru.setLayout(pnl_editGuruLayout);
        pnl_editGuruLayout.setHorizontalGroup(
            pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_pembatas, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnl_editGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_editGuruLayout.createSequentialGroup()
                        .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_editGuruLayout.createSequentialGroup()
                                .addComponent(lbl_alamat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnl_editGuruLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(93, 93, 93)))
                        .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nomorTelepon)))
                    .addGroup(pnl_editGuruLayout.createSequentialGroup()
                        .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_kodeGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_kodeGuru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_namaGuru)))
                    .addGroup(pnl_editGuruLayout.createSequentialGroup()
                        .addComponent(lbl_editGuru)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_editGuruLayout.createSequentialGroup()
                        .addComponent(btn_editData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93)
                        .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_editGuruLayout.setVerticalGroup(
            pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_editGuruLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_editGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_pembatas, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kodeGuru)
                    .addComponent(lbl_namaGuru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_kodeGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_editGuruLayout.createSequentialGroup()
                        .addComponent(lbl_alamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_editGuruLayout.createSequentialGroup()
                        .addComponent(lbl_nomorTelepon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(pnl_editGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editData, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_editGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_editGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        guru gr = new guru();
        gr.show();
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editData;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_editGuru;
    private javax.swing.JLabel lbl_kodeGuru;
    private javax.swing.JLabel lbl_namaGuru;
    private javax.swing.JLabel lbl_nomorTelepon;
    private javax.swing.JPanel pnl_editGuru;
    private javax.swing.JSeparator sp_pembatas;
    private javax.swing.JTextField tf_kodeGuru;
    private javax.swing.JTextField tf_namaGuru;
    private javax.swing.JTextField tf_nomorTelepon;
    // End of variables declaration//GEN-END:variables
}
