package dashboard;


import guru.guru;
import jadwal.jadwal;
import mapel.mapel;
import murid.murid;
import rapot.rapot;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arif Rachmat Darmawa
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_dashboard = new javax.swing.JPanel();
        lbl_selamatDatang = new javax.swing.JLabel();
        lbl_selamatDatang2 = new javax.swing.JLabel();
        sp_pembatas = new javax.swing.JSeparator();
        pnl_dataGuru = new javax.swing.JPanel();
        btn_dataGuru = new javax.swing.JButton();
        pnl_dataJadwal = new javax.swing.JPanel();
        btn_dataJadwal = new javax.swing.JButton();
        pnl_dataMapel = new javax.swing.JPanel();
        btn_dataMapel = new javax.swing.JButton();
        pnl_dataMurid = new javax.swing.JPanel();
        btn_dataMurid = new javax.swing.JButton();
        pnl_dataRapot = new javax.swing.JPanel();
        btn_dataRapot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_dashboard.setBackground(new java.awt.Color(255, 255, 255));

        lbl_selamatDatang.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_selamatDatang.setText("Selamat Datang");

        lbl_selamatDatang2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_selamatDatang2.setForeground(new java.awt.Color(0, 140, 186));
        lbl_selamatDatang2.setText("Di Aplikasi MySchool!");

        pnl_dataGuru.setBackground(new java.awt.Color(0, 0, 0));

        btn_dataGuru.setBackground(new java.awt.Color(255, 255, 255));
        btn_dataGuru.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_dataGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/ic_guru.png"))); // NOI18N
        btn_dataGuru.setText("  Data Guru");
        btn_dataGuru.setToolTipText("");
        btn_dataGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataGuruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_dataGuruLayout = new javax.swing.GroupLayout(pnl_dataGuru);
        pnl_dataGuru.setLayout(pnl_dataGuruLayout);
        pnl_dataGuruLayout.setHorizontalGroup(
            pnl_dataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataGuruLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_dataGuru)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnl_dataGuruLayout.setVerticalGroup(
            pnl_dataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataGuruLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_dataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnl_dataJadwal.setBackground(new java.awt.Color(0, 0, 0));

        btn_dataJadwal.setBackground(new java.awt.Color(255, 255, 255));
        btn_dataJadwal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_dataJadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/ic_jadwal.png"))); // NOI18N
        btn_dataJadwal.setText("  Data Jadwal");
        btn_dataJadwal.setToolTipText("");
        btn_dataJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataJadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_dataJadwalLayout = new javax.swing.GroupLayout(pnl_dataJadwal);
        pnl_dataJadwal.setLayout(pnl_dataJadwalLayout);
        pnl_dataJadwalLayout.setHorizontalGroup(
            pnl_dataJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataJadwalLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_dataJadwal)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnl_dataJadwalLayout.setVerticalGroup(
            pnl_dataJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataJadwalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_dataJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnl_dataMapel.setBackground(new java.awt.Color(0, 0, 0));

        btn_dataMapel.setBackground(new java.awt.Color(255, 255, 255));
        btn_dataMapel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_dataMapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/ic_mapel.png"))); // NOI18N
        btn_dataMapel.setText("  Data Mapel");
        btn_dataMapel.setToolTipText("");
        btn_dataMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataMapelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_dataMapelLayout = new javax.swing.GroupLayout(pnl_dataMapel);
        pnl_dataMapel.setLayout(pnl_dataMapelLayout);
        pnl_dataMapelLayout.setHorizontalGroup(
            pnl_dataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataMapelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_dataMapel)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnl_dataMapelLayout.setVerticalGroup(
            pnl_dataMapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataMapelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_dataMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnl_dataMurid.setBackground(new java.awt.Color(0, 0, 0));

        btn_dataMurid.setBackground(new java.awt.Color(255, 255, 255));
        btn_dataMurid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_dataMurid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/ic_murid.png"))); // NOI18N
        btn_dataMurid.setText("  Data Murid");
        btn_dataMurid.setToolTipText("");
        btn_dataMurid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataMuridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_dataMuridLayout = new javax.swing.GroupLayout(pnl_dataMurid);
        pnl_dataMurid.setLayout(pnl_dataMuridLayout);
        pnl_dataMuridLayout.setHorizontalGroup(
            pnl_dataMuridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataMuridLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_dataMurid)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnl_dataMuridLayout.setVerticalGroup(
            pnl_dataMuridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataMuridLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_dataMurid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnl_dataRapot.setBackground(new java.awt.Color(0, 0, 0));

        btn_dataRapot.setBackground(new java.awt.Color(255, 255, 255));
        btn_dataRapot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_dataRapot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/ic_rapot.png"))); // NOI18N
        btn_dataRapot.setText("  Data Rapot");
        btn_dataRapot.setToolTipText("");
        btn_dataRapot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataRapotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_dataRapotLayout = new javax.swing.GroupLayout(pnl_dataRapot);
        pnl_dataRapot.setLayout(pnl_dataRapotLayout);
        pnl_dataRapotLayout.setHorizontalGroup(
            pnl_dataRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataRapotLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_dataRapot)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnl_dataRapotLayout.setVerticalGroup(
            pnl_dataRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dataRapotLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_dataRapot, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_dashboardLayout = new javax.swing.GroupLayout(pnl_dashboard);
        pnl_dashboard.setLayout(pnl_dashboardLayout);
        pnl_dashboardLayout.setHorizontalGroup(
            pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_pembatas)
            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_dashboardLayout.createSequentialGroup()
                        .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                                .addComponent(pnl_dataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(pnl_dataJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(pnl_dataMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                                .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_selamatDatang)
                                    .addComponent(lbl_selamatDatang2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pnl_dashboardLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(pnl_dataMurid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_dataRapot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );
        pnl_dashboardLayout.setVerticalGroup(
            pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_selamatDatang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_selamatDatang2)
                .addGap(18, 18, 18)
                .addComponent(sp_pembatas, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_dataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_dataJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_dataMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_dataMurid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_dataRapot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dataJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataJadwalActionPerformed
        jadwal jdw = new jadwal();
        jdw.show();
        
        dispose();
    }//GEN-LAST:event_btn_dataJadwalActionPerformed

    private void btn_dataGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataGuruActionPerformed
        guru gr = new guru();
        gr.show();
        
        dispose();
    }//GEN-LAST:event_btn_dataGuruActionPerformed

    private void btn_dataMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataMapelActionPerformed
        // TODO add your handling code here:
        mapel mpl = new mapel();
        mpl.show();
        
        dispose();
    }//GEN-LAST:event_btn_dataMapelActionPerformed

    private void btn_dataMuridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataMuridActionPerformed
        // TODO add your handling code here:
        murid mrd = new murid();
        mrd.show();
        
        dispose();
    }//GEN-LAST:event_btn_dataMuridActionPerformed

    private void btn_dataRapotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataRapotActionPerformed
        // TODO add your handling code here:
        rapot rpt = new rapot();
        rpt.show();
        
        dispose();
    }//GEN-LAST:event_btn_dataRapotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dataGuru;
    private javax.swing.JButton btn_dataJadwal;
    private javax.swing.JButton btn_dataMapel;
    private javax.swing.JButton btn_dataMurid;
    private javax.swing.JButton btn_dataRapot;
    private javax.swing.JLabel lbl_selamatDatang;
    private javax.swing.JLabel lbl_selamatDatang2;
    private javax.swing.JPanel pnl_dashboard;
    private javax.swing.JPanel pnl_dataGuru;
    private javax.swing.JPanel pnl_dataJadwal;
    private javax.swing.JPanel pnl_dataMapel;
    private javax.swing.JPanel pnl_dataMurid;
    private javax.swing.JPanel pnl_dataRapot;
    private javax.swing.JSeparator sp_pembatas;
    // End of variables declaration//GEN-END:variables
}
