/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapot;

/**
 *
 * @author Arif Rachmat Darmawa
 */
public class tambah_rapot extends javax.swing.JFrame {

    /**
     * Creates new form tambah_rapot
     */
    public tambah_rapot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_tambahRapot = new javax.swing.JPanel();
        lbl_tambahRapot = new javax.swing.JLabel();
        sp_pembatas = new javax.swing.JSeparator();
        nis = new javax.swing.JLabel();
        tf_nis = new javax.swing.JTextField();
        lbl_namaMapel = new javax.swing.JLabel();
        tf_namaMapel = new javax.swing.JTextField();
        lbl_tahunAkademik = new javax.swing.JLabel();
        tf_tahunAkademik = new javax.swing.JTextField();
        lbl_semester = new javax.swing.JLabel();
        tf_semester = new javax.swing.JTextField();
        lbl_nilai = new javax.swing.JLabel();
        tf_nilai = new javax.swing.JTextField();
        btn_tambahData = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_tambahRapot.setBackground(new java.awt.Color(255, 255, 255));

        lbl_tambahRapot.setBackground(new java.awt.Color(0, 0, 0));
        lbl_tambahRapot.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_tambahRapot.setText("Tambah Rapot");

        nis.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nis.setText("NIS");

        tf_nis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_namaMapel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_namaMapel.setText("Mata Pelajaran");

        tf_namaMapel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_namaMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_namaMapelActionPerformed(evt);
            }
        });

        lbl_tahunAkademik.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_tahunAkademik.setText("Tahun Akademik");

        tf_tahunAkademik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_semester.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_semester.setText("Semester");

        tf_semester.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_nilai.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_nilai.setText("Nilai");

        tf_nilai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_tambahData.setBackground(new java.awt.Color(0, 140, 186));
        btn_tambahData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_tambahData.setText("Tambah Data");

        btn_kembali.setBackground(new java.awt.Color(244, 67, 54));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_tambahRapotLayout = new javax.swing.GroupLayout(pnl_tambahRapot);
        pnl_tambahRapot.setLayout(pnl_tambahRapotLayout);
        pnl_tambahRapotLayout.setHorizontalGroup(
            pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_pembatas, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnl_tambahRapotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tambahRapotLayout.createSequentialGroup()
                        .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_namaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_namaMapel)))
                    .addGroup(pnl_tambahRapotLayout.createSequentialGroup()
                        .addComponent(btn_tambahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93)
                        .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_tambahRapotLayout.createSequentialGroup()
                        .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tahunAkademik)
                            .addComponent(lbl_tambahRapot)
                            .addComponent(tf_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_tahunAkademik, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nilai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_semester))))
                .addContainerGap())
        );
        pnl_tambahRapotLayout.setVerticalGroup(
            pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tambahRapotLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tambahRapot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_pembatas, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nis)
                    .addComponent(lbl_namaMapel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_namaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tambahRapotLayout.createSequentialGroup()
                        .addComponent(lbl_tahunAkademik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tahunAkademik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_tambahRapotLayout.createSequentialGroup()
                        .addComponent(lbl_semester)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lbl_nilai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pnl_tambahRapotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_tambahRapot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_tambahRapot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        rapot rpt = new rapot();
        rpt.show();
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void tf_namaMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namaMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_namaMapelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_rapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_rapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_rapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_rapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambah_rapot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambahData;
    private javax.swing.JLabel lbl_namaMapel;
    private javax.swing.JLabel lbl_nilai;
    private javax.swing.JLabel lbl_semester;
    private javax.swing.JLabel lbl_tahunAkademik;
    private javax.swing.JLabel lbl_tambahRapot;
    private javax.swing.JLabel nis;
    private javax.swing.JPanel pnl_tambahRapot;
    private javax.swing.JSeparator sp_pembatas;
    private javax.swing.JTextField tf_namaMapel;
    private javax.swing.JTextField tf_nilai;
    private javax.swing.JTextField tf_nis;
    private javax.swing.JTextField tf_semester;
    private javax.swing.JTextField tf_tahunAkademik;
    // End of variables declaration//GEN-END:variables
}
