/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapel;

/**
 *
 * @author Arif Rachmat Darmawa
 */
public class edit_mapel extends javax.swing.JFrame {

    /**
     * Creates new form edit_mapel
     */
    public edit_mapel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_editMataPelajaran = new javax.swing.JPanel();
        lbl_editMataPelajaran = new javax.swing.JLabel();
        sp_pembatas = new javax.swing.JSeparator();
        lbl_kodeMapel = new javax.swing.JLabel();
        tf_kodeMapel = new javax.swing.JTextField();
        lbl_namaMapel = new javax.swing.JLabel();
        tf_namaMapel = new javax.swing.JTextField();
        lbl_namaGuru = new javax.swing.JLabel();
        tf_kodeGuru = new javax.swing.JTextField();
        btn_editData = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_editMataPelajaran.setBackground(new java.awt.Color(255, 255, 255));

        lbl_editMataPelajaran.setBackground(new java.awt.Color(0, 0, 0));
        lbl_editMataPelajaran.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_editMataPelajaran.setText("Edit Mata Pelajaran");

        lbl_kodeMapel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_kodeMapel.setText("Kode Mata Pelajaran ( Contoh Penamaan : KDG_001 )");

        tf_kodeMapel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_namaMapel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_namaMapel.setText("Nama Mata Pelajaran");

        tf_namaMapel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_namaGuru.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_namaGuru.setText("Nama Guru");

        tf_kodeGuru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_editData.setBackground(new java.awt.Color(0, 140, 186));
        btn_editData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_editData.setText("Edit Data");

        btn_kembali.setBackground(new java.awt.Color(244, 67, 54));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_editMataPelajaranLayout = new javax.swing.GroupLayout(pnl_editMataPelajaran);
        pnl_editMataPelajaran.setLayout(pnl_editMataPelajaranLayout);
        pnl_editMataPelajaranLayout.setHorizontalGroup(
            pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_pembatas, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnl_editMataPelajaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_editMataPelajaranLayout.createSequentialGroup()
                        .addGroup(pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_kodeMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_kodeMapel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_namaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_namaMapel)))
                    .addGroup(pnl_editMataPelajaranLayout.createSequentialGroup()
                        .addComponent(btn_editData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93)
                        .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_editMataPelajaranLayout.createSequentialGroup()
                        .addGroup(pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_editMataPelajaran)
                            .addComponent(tf_kodeGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_namaGuru))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_editMataPelajaranLayout.setVerticalGroup(
            pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_editMataPelajaranLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_editMataPelajaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_pembatas, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kodeMapel)
                    .addComponent(lbl_namaMapel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_kodeMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_namaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_namaGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_kodeGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pnl_editMataPelajaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editData, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_editMataPelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_editMataPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        mapel mpl = new mapel();
        mpl.show();
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_mapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_mapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_mapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_mapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_mapel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editData;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JLabel lbl_editMataPelajaran;
    private javax.swing.JLabel lbl_kodeMapel;
    private javax.swing.JLabel lbl_namaGuru;
    private javax.swing.JLabel lbl_namaMapel;
    private javax.swing.JPanel pnl_editMataPelajaran;
    private javax.swing.JSeparator sp_pembatas;
    private javax.swing.JTextField tf_kodeGuru;
    private javax.swing.JTextField tf_kodeMapel;
    private javax.swing.JTextField tf_namaMapel;
    // End of variables declaration//GEN-END:variables
}
