/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jadwal;

import guru.guru;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Arif Rachmat Darmawa
 */
public class edit_jadwal extends javax.swing.JFrame {
    static Statement stmt;
    static Connection conn;
    static ResultSet resultSet;
    /**
     * Creates new form edit_jadwal
     * @param kd_mapel
     * @param kd_guru
     * @param nama_mapel
     * @param hari
     * @param jam
     */
    public edit_jadwal(String kd_mapel, String kd_guru, String nama_mapel, String harihari, String jamjam) {
        initComponents();
        kodeMapel.setText(kd_mapel);
        namaGuru.setText(kd_guru);
        namaMapel.setText(nama_mapel);
        hari.setText(harihari);
        jam.setText(jamjam);
    }

    private edit_jadwal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_editJadwal = new javax.swing.JPanel();
        lbl_editJadwal = new javax.swing.JLabel();
        sp_pembatas = new javax.swing.JSeparator();
        lbl_kodeMapel = new javax.swing.JLabel();
        lbl_namaGuru = new javax.swing.JLabel();
        lbl_namaMapel = new javax.swing.JLabel();
        namaMapel = new javax.swing.JTextField();
        lbl_hari = new javax.swing.JLabel();
        hari = new javax.swing.JTextField();
        lbl_jam = new javax.swing.JLabel();
        jam = new javax.swing.JTextField();
        editData = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        kodeMapel = new javax.swing.JLabel();
        namaGuru = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_editJadwal.setBackground(new java.awt.Color(255, 255, 255));

        lbl_editJadwal.setBackground(new java.awt.Color(0, 0, 0));
        lbl_editJadwal.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_editJadwal.setText("Edit Jadwal");

        lbl_kodeMapel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_kodeMapel.setText("Kode Mata Pelajaran ( Contoh Penamaan : KDM_001 )");

        lbl_namaGuru.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_namaGuru.setText("Nama Guru");

        lbl_namaMapel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_namaMapel.setText("Nama Mata Pelajaran");

        namaMapel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namaMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMapelActionPerformed(evt);
            }
        });

        lbl_hari.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_hari.setText("Hari");

        hari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_jam.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_jam.setText("Jam");

        jam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        editData.setBackground(new java.awt.Color(0, 140, 186));
        editData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editData.setText("Edit Data");
        editData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataActionPerformed(evt);
            }
        });

        btn_kembali.setBackground(new java.awt.Color(244, 67, 54));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_editJadwalLayout = new javax.swing.GroupLayout(pnl_editJadwal);
        pnl_editJadwal.setLayout(pnl_editJadwalLayout);
        pnl_editJadwalLayout.setHorizontalGroup(
            pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_pembatas, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                        .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_editJadwal)
                            .addComponent(lbl_kodeMapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kodeMapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                                .addComponent(lbl_namaGuru)
                                .addGap(397, 397, 397))
                            .addComponent(namaGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                        .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                                .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editData, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_namaMapel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                                .addComponent(namaMapel)
                                .addGap(93, 93, 93)))
                        .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hari)
                            .addComponent(lbl_hari)
                            .addComponent(btn_kembali, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))
                    .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                        .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_jam)
                            .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_editJadwalLayout.setVerticalGroup(
            pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_editJadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_pembatas, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kodeMapel)
                    .addComponent(lbl_namaGuru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                        .addComponent(kodeMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                                .addComponent(lbl_hari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                                .addComponent(lbl_namaMapel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_jam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(pnl_editJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editData, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(pnl_editJadwalLayout.createSequentialGroup()
                        .addComponent(namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_editJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_editJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        jadwal jdw = new jadwal();
        jdw.show();
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void namaMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaMapelActionPerformed

    private void editDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataActionPerformed
        // TODO add your handling code here:
        Config con = new Config();
        String query = "UPDATE jadwal SET nama_mapel = ?, hari = ?, jam = ? WHERE kd_mapel = ?";
        con.dbConnect();
        
        try{
            PreparedStatement psUpdate = Config.conn.prepareStatement(query);
            psUpdate.setString(1, namaMapel.getText());
            psUpdate.setString(2, hari.getText());
            psUpdate.setString(3, jam.getText());
            psUpdate.setString(4, kodeMapel.getText());
            psUpdate.execute();
            JOptionPane.showMessageDialog(null, "Data Sukses diupdate");
            jadwal gr = new jadwal();
            gr.show();
            dispose();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal diupdate "+e);
            jadwal gr = new jadwal();
            gr.show();
            dispose();
        }
    }//GEN-LAST:event_editDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new edit_jadwal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton editData;
    private javax.swing.JTextField hari;
    private javax.swing.JTextField jam;
    private javax.swing.JLabel kodeMapel;
    private javax.swing.JLabel lbl_editJadwal;
    private javax.swing.JLabel lbl_hari;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_kodeMapel;
    private javax.swing.JLabel lbl_namaGuru;
    private javax.swing.JLabel lbl_namaMapel;
    private javax.swing.JLabel namaGuru;
    private javax.swing.JTextField namaMapel;
    private javax.swing.JPanel pnl_editJadwal;
    private javax.swing.JSeparator sp_pembatas;
    // End of variables declaration//GEN-END:variables
}
