/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jadwal;

/**
 *
 * @author Arif Rachmat Darmawa
 */
public class tambah_jadwal extends javax.swing.JFrame {

    /**
     * Creates new form tambah_jadwal
     */
    public tambah_jadwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_tambahJadwal = new javax.swing.JPanel();
        lbl_tambahJadwal = new javax.swing.JLabel();
        sp_pembatas = new javax.swing.JSeparator();
        lbl_kodeMapel = new javax.swing.JLabel();
        tf_kodeMapel = new javax.swing.JTextField();
        lbl_namaGuru = new javax.swing.JLabel();
        cmb_namaGuru = new javax.swing.JComboBox<>();
        lbl_namaMapel = new javax.swing.JLabel();
        tf_namaMapel = new javax.swing.JTextField();
        lbl_hari = new javax.swing.JLabel();
        tf_hari = new javax.swing.JTextField();
        lbl_jam = new javax.swing.JLabel();
        tf_jam = new javax.swing.JTextField();
        btn_tambahData = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_tambahJadwal.setBackground(new java.awt.Color(255, 255, 255));

        lbl_tambahJadwal.setBackground(new java.awt.Color(0, 0, 0));
        lbl_tambahJadwal.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_tambahJadwal.setText("Tambah Jadwal");

        lbl_kodeMapel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_kodeMapel.setText("Kode Mata Pelajaran ( Contoh Penamaan : KDM_001 )");

        tf_kodeMapel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_namaGuru.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_namaGuru.setText("Nama Guru");

        cmb_namaGuru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_namaGuru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nita Moha, S.Pd", "Acep Surecep, S.Pd", "Anang Dinata, S.Pd", "Bagus Sudrajat, S.Pd" }));

        lbl_namaMapel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_namaMapel.setText("Nama Mata Pelajaran");

        tf_namaMapel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_hari.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_hari.setText("Hari");

        tf_hari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_jam.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_jam.setText("Jam");

        tf_jam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_tambahData.setBackground(new java.awt.Color(0, 140, 186));
        btn_tambahData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_tambahData.setText("Tambah Data");

        btn_kembali.setBackground(new java.awt.Color(244, 67, 54));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_tambahJadwalLayout = new javax.swing.GroupLayout(pnl_tambahJadwal);
        pnl_tambahJadwal.setLayout(pnl_tambahJadwalLayout);
        pnl_tambahJadwalLayout.setHorizontalGroup(
            pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_pembatas, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnl_tambahJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tambahJadwalLayout.createSequentialGroup()
                        .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_kodeMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tambahJadwal)
                            .addComponent(lbl_kodeMapel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_tambahJadwalLayout.createSequentialGroup()
                                .addComponent(lbl_namaGuru)
                                .addGap(397, 397, 397))
                            .addComponent(cmb_namaGuru, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl_tambahJadwalLayout.createSequentialGroup()
                        .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_namaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_namaMapel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_hari)
                            .addComponent(lbl_hari)
                            .addComponent(btn_kembali, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))
                    .addGroup(pnl_tambahJadwalLayout.createSequentialGroup()
                        .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_jam)
                            .addComponent(tf_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_tambahJadwalLayout.setVerticalGroup(
            pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tambahJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tambahJadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_pembatas, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kodeMapel)
                    .addComponent(lbl_namaGuru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kodeMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tambahJadwalLayout.createSequentialGroup()
                        .addComponent(lbl_hari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_hari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_tambahJadwalLayout.createSequentialGroup()
                        .addComponent(lbl_namaMapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_namaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lbl_jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(pnl_tambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_tambahJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_tambahJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        jadwal jdw = new jadwal();
        jdw.show();
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambah_jadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambahData;
    private javax.swing.JComboBox<String> cmb_namaGuru;
    private javax.swing.JLabel lbl_hari;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_kodeMapel;
    private javax.swing.JLabel lbl_namaGuru;
    private javax.swing.JLabel lbl_namaMapel;
    private javax.swing.JLabel lbl_tambahJadwal;
    private javax.swing.JPanel pnl_tambahJadwal;
    private javax.swing.JSeparator sp_pembatas;
    private javax.swing.JTextField tf_hari;
    private javax.swing.JTextField tf_jam;
    private javax.swing.JTextField tf_kodeMapel;
    private javax.swing.JTextField tf_namaMapel;
    // End of variables declaration//GEN-END:variables
}
